
name = "crazy-art"
pages_build_output_dir = "dist"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "crazyart-db"
database_id = "f0a05c7b-af49-449a-a9d7-280e94e15865" # SUBSTITUA PELO ID REAL ENCONTRADO NO DASHBOARD

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "crazyart-images"

[vars]
R2_PUBLIC_URL = "https://imagens.crazyart.com.br"
